### ISSUE TITLE
mod is requesting version of Ex Nihilo Sequentia that hasn't been released yet

### ISSUE THREAD

**Issue by superdude808** [PersiflageTheNinth/TetraNihilo#1]
same as title tetra nihilo is requiring Ex Nihilo Sequentia 4.2.0 or above which has not been released yet

what is currently availiable  is 1.19.2-4.1.0.55-beta from the curseforge and is also stated at the bottom of Ex Nihilo Sequentia's github page about compatibility involving the use of its api 

easy mistake to make if you just checked their github's recent updates and code commits without talking to the people making the mod not everyone has time for that after-all

**Comment by PersiflageTheNinth** [comment]
At the time I made the requirement that was the latest version on curseforge. It was de-listed later. I will have a fixed build up soon

**Comment by superdude808** [comment]
thanks for fixing this I actually thought your compat was a neat idea

**Comment by PersiflageTheNinth** [comment]
Crooks are still on my to-do as well. Have to actually design the tetra version of the tools still.
Have all the loot/technical logic done already as they're so similar hammers and crooks

**Comment by PersiflageTheNinth** [comment]
New version pending on curseforge, thanks for the report!
